---
- name: FMG API - Replace SN for device {{ device[0] }}
  fmgr_dvmdb_device_replace_sn:
    adom: "{{ fmg_adom }}"
    device_name: "{{ device[0] }}"
    rc_succeeded:
      - -20010
    dvmdb_device_replace_sn:
      sn: "{{ device[1] }}"

- name: FMG API - Update FGFM credentials for device {{ device[0] }}
  fmgr_dvmdb_device:
    adom: "{{ fmg_adom }}"
    device: "{{ device[0] }}"
    dvmdb_device:
      adm_usr: "{{ fgfm_admin }}"
      adm_pass: "{{ fgfm_password }}"
  
- name: FMG API - Update FMG SN for device {{ device[0] }}
  fmgr_exec_fgfm_reclaimdevtunnel:
    device_name: "{{ device[0] }}"
    exec_fgfm_reclaimdevtunnel:
      flags:
        - force