---
- name: FPOC API - Login to FortiPoC
  uri:
    method: post
    url: "{{ fpoc_url_prefix }}/v0/login"
    validate_certs: false
    body_format: json
    body:
      username: "{{ fpoc_username }}"
      password: "{{ fpoc_password }}"
  register: fpoc_session

- name: ANSIBLE - Saving cookies
  set_fact:
    fpoc_cookies: "{{ fpoc_session.cookies_string }}"

- name: DEBUG
  debug:
    msg: "{{ fpoc_cookies }}"
  when: debug_enabled
