---
- name: 'FPOC API - Get list of managed devices'
  uri:
    url: '{{ fpoc_url_prefix }}/login'
    validate_certs: false
    body_format: json
    method: post
    body:
      username: '{{ fpoc_username }}'
      password: '{{ fpoc_password }}'
- name: Create workspaces in Log analytics Azure
  uri:
    url: https://www.mms.microsoft.com/Embedded/Api/ConfigDataSources/LogManagementData/Save
    method: POST
    body_format: json
    status_code: [200, 202]
    return_content: true
    headers:
      Content-Type: application/json
      x-ms-client-workspace-path: /subscriptions/{{ sub_id }}/resourcegroups/{{ res_group }}/providers/microsoft.operationalinsights/workspaces/{{ w_spaces }}
      x-ms-client-platform: ibiza
      x-ms-client-auth-token: "{{ token_az }}"
    body: