---
- name: Fix FortiManager SN issue
  connection: httpapi
  hosts: FMG
  collections:
    - fortinet.fortimanager
  
  tasks:
    - name: Login to FortiPoC
      include_tasks: tasks/fpoc_login.yml

    - name: Get Managed Devices Serial Number
      include_tasks: tasks/fpoc_get_managed_devices_sn.yml

    - name: Logout from FortiPoC
      include_tasks: tasks/fpoc_logout.yml

    - name: Fix SN in FMG
      include_tasks: tasks/fmg_fix_sn.yml
      loop: "{{ final }}"
      loop_control:
        loop_var: device

    - name: Re-install Policy Packages for all devices except the FAZ
      include_tasks: tasks/reinstall_ppkgs.yml
      loop: "{{ fmg_ppkgs }}"
      loop_control:
        loop_var: ppkg